name: RTL CI AUTO MERGE

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  simulate-and-merge:
    if: github.actor != 'github-actions[bot]'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Simulation
        run: unset VERILATOR_ROOT && make all

      - name: Configure Git
        run: |
          git config --global user.name github-actions
          git config --global user.email actions@github.com

      - name: Create Temp Branch
        run: git checkout -b auto-temp

      - name: Checkout Main
        run: git checkout main

      - name: Merge Temp Branch
        run: |
          git merge --no-ff auto-temp \
          -m "Auto merge after CI success"

      - name: Push Main
        run: git push origin main
